/* PASSO 1: CRIAR O BANCO DE DADOS */
CREATE DATABASE 'C:\Projetos\Projeto Cadastro Funcionarios Dass\Base de dados\FUNCIONARIOS_DASS.fdb' 
USER 'SYSDBA' PASSWORD 'masterkey' 
PAGE_SIZE 8192 
DEFAULT CHARACTER SET WIN1252;

/* PASSO 2: CRIAR A TABELA */
CREATE TABLE FUNCIONARIOS (
    ID INTEGER NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(14) NOT NULL,
    EMAIL VARCHAR(100),
    TAMANHO_CAMISA VARCHAR(2),
    TAMANHO_CALCADO INTEGER,
    CONSTRAINT PK_FUNCIONARIOS PRIMARY KEY (ID),
    CONSTRAINT UNQ_CPF UNIQUE (CPF)
);

/* PASSO 3: CRIAR O GENERATOR (SEQUENCIA) */
CREATE SEQUENCE GEN_FUNCIONARIOS_ID;


/* PASSO 4: INSERÇÃO DE 10 REGISTROS */
INSERT INTO FUNCIONARIOS (ID, NOME, CPF, EMAIL, TAMANHO_CAMISA, TAMANHO_CALCADO)
VALUES (GEN_ID(GEN_FUNCIONARIOS_ID, 1), 'ANA BEATRIZ SILVA', '13524678901', 'ana.silva@dass.com.br', 'P', 35);

INSERT INTO FUNCIONARIOS (ID, NOME, CPF, EMAIL, TAMANHO_CAMISA, TAMANHO_CALCADO)
VALUES (GEN_ID(GEN_FUNCIONARIOS_ID, 1), 'BRUNO OLIVEIRA', '24635789012', 'bruno.oliveira@dass.com.br', 'GG', 42);

INSERT INTO FUNCIONARIOS (ID, NOME, CPF, EMAIL, TAMANHO_CAMISA, TAMANHO_CALCADO)
VALUES (GEN_ID(GEN_FUNCIONARIOS_ID, 1), 'CARLA MENDONCA', '35746890123', 'carla.m@dass.com.br', 'M', 37);

INSERT INTO FUNCIONARIOS (ID, NOME, CPF, EMAIL, TAMANHO_CAMISA, TAMANHO_CALCADO)
VALUES (GEN_ID(GEN_FUNCIONARIOS_ID, 1), 'DIEGO FERNANDES', '46857901234', 'diego.f@dass.com.br', 'G', 40);

INSERT INTO FUNCIONARIOS (ID, NOME, CPF, EMAIL, TAMANHO_CAMISA, TAMANHO_CALCADO)
VALUES (GEN_ID(GEN_FUNCIONARIOS_ID, 1), 'ELENA RODRIGUES', '57968012345', 'elena.r@dass.com.br', 'P', 36);

INSERT INTO FUNCIONARIOS (ID, NOME, CPF, EMAIL, TAMANHO_CAMISA, TAMANHO_CALCADO)
VALUES (GEN_ID(GEN_FUNCIONARIOS_ID, 1), 'FABIO JUNIOR SANTOS', '68079123456', 'fabio.santos@dass.com.br', 'M', 39);

INSERT INTO FUNCIONARIOS (ID, NOME, CPF, EMAIL, TAMANHO_CAMISA, TAMANHO_CALCADO)
VALUES (GEN_ID(GEN_FUNCIONARIOS_ID, 1), 'GISELE BUNDCHEN', '79180234567', 'gisele.b@dass.com.br', 'M', 38);

INSERT INTO FUNCIONARIOS (ID, NOME, CPF, EMAIL, TAMANHO_CAMISA, TAMANHO_CALCADO)
VALUES (GEN_ID(GEN_FUNCIONARIOS_ID, 1), 'HUGO LEONARDO', '80291345678', 'hugo.l@dass.com.br', 'G', 41);

INSERT INTO FUNCIONARIOS (ID, NOME, CPF, EMAIL, TAMANHO_CAMISA, TAMANHO_CALCADO)
VALUES (GEN_ID(GEN_FUNCIONARIOS_ID, 1), 'IARA CAVALCANTE', '91302456789', 'iara.c@dass.com.br', 'P', 34);

INSERT INTO FUNCIONARIOS (ID, NOME, CPF, EMAIL, TAMANHO_CAMISA, TAMANHO_CALCADO)
VALUES (GEN_ID(GEN_FUNCIONARIOS_ID, 1), 'JOAO PEDRO ROCHA', '02413567890', 'joao.rocha@dass.com.br', 'GG', 43);

COMMIT;